#!/bin/bash

echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the dynamixel configurator connection as /dev/ttyUSB?."
echo ""

sudo cp `rospack find dynamixel_driver`/scripts/58-dynamixel_configurator.rules /etc/udev/rules.d


echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart

